name: AltitudeTracker
options:
  bundleIdPrefix: com.thepoka
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""          # Xcode will prompt you to set this
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  AltitudeTracker:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AltitudeTracker
        excludes:
          - "Info.plist"
    info:
      path: AltitudeTracker/Info.plist
      properties:
        NSLocationWhenInUseUsageDescription: "AltitudeTracker uses your location to record GPS coordinates and altitude along your route."
        NSLocationAlwaysAndWhenInUseUsageDescription: "AltitudeTracker uses your location in the background to continue recording altitude when the app is not in the foreground."
        NSMotionUsageDescription: "AltitudeTracker uses the barometric altimeter for more accurate altitude readings."
        UIBackgroundModes:
          - location
        UIRequiredDeviceCapabilities:
          - location-services
          - gps
        UILaunchScreen: {}
        CFBundleDisplayName: AltitudeTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.thepoka.AltitudeTracker
        INFOPLIST_FILE: AltitudeTracker/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies: []
    scheme:
      testTargets: []
